#ifndef __TETRIS_GAMECONFIG_H__
#define __TETRIS_GAMECONFIG_H__

#define TETRIS_COLUMN_NUMBER	10
#define TETRIS_ROW_NUMBER		15
#define TETRIS_ROW_FILLED_FLAG	0x03FF


#endif // __TETRIS_GAMECONFIG_H__
